# Generated by Django 5.0.5 on 2024-05-22 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
