# Generated by Django 5.0.5 on 2024-05-23 04:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminAcc',
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
        migrations.DeleteModel(
            name='UserAcc',
        ),
        migrations.AlterField(
            model_name='book',
            name='bPublishDate',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 5, 23))]),
        ),
    ]
