# Generated by Django 5.0.5 on 2024-05-23 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_delete_adminacc_delete_signup_delete_useracc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.profile'),
        ),
    ]
