# Generated by Django 5.0.5 on 2024-05-24 03:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_borrowrecord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bPublishDate',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 5, 24))]),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='duration',
            field=models.IntegerField(max_length=50),
        ),
    ]
