# Generated by Django 5.0.5 on 2024-05-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_book_bpublishdate_alter_borrowrecord_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='return_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
