# Generated by Django 5.0.5 on 2024-05-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_borrowrecord_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='return_date',
            field=models.DateTimeField(blank=True, default=''),
        ),
    ]
